services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=petsafe-dev
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080